name: flutter_lab3
description: Лабораторная работа №3 - основные элементы UI во Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
